version: 2
jobs:
  publish:
    docker:
      - image: alpine:3.11
    environment:
      DOCKER_USERNAME: secrethub://simon/test/docker/username
      DOCKER_PASSWORD: secrethub://simon/test/docker/password
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install SecretHub CLI
          command: apk add --repository https://alpine.secrethub.io/alpine/edge/main --allow-untrusted secrethub-cli
      - run:
          name: Build Docker image
          command: docker build -t florisvdg/ci-test:$CIRCLE_SHA1 .
      - run:
          name: Authenticate to DockerHub
          shell: secrethub run -- /bin/bash
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Publish on DockerHub
          command: docker push florisvdg/ci-test:$CIRCLE_SHA1
workflows:
  version: 2
  pipeline:
    jobs:
      - publish
