version: 2
jobs:
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKER_USERNAME: secrethub://simon/test/docker/username
      DOCKER_PASSWORD: secrethub://simon/test/docker/password
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install SecretHub CLI
          environment:
            VERSION: 0.34.0
          command: curl -sSfL https://github.com/secrethub/secrethub-cli/releases/download/v$VERSION/secrethub-v$VERSION-linux-amd64.tar.gz | tar zxf - -C $HOME
      - run:
          name: Build Docker image
          command: docker build -t florisvdg/ci-test:$CIRCLE_SHA1 .
      - run:
          name: Authenticate to DockerHub
          shell: secrethub run /bin/bash
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Publish on DockerHub
          command: docker push florisvdg/ci-test:$CIRCLE_SHA1
workflows:
  version: 2
  pipeline:
    jobs:
      - publish
